### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aryan9592**
Fixed some mistakes in the README

### CODE REVIEW

**Comment by adamunchained** [comment]
Thank you! @Aryan9592

**Comment by adamunchained** [comment]
@Aryan9592 - can you share your smr address? We'll reward you with 10 SOON for this small contribution. I know it might not be much but I want to show you that we appreciate every single one.

**Comment by Aryan9592** [comment]
Well, thanks!!

Here's my smr address

wallet

**Comment by adamunchained** [comment]
> Well, thanks!!
> 
> 
> 
> Here's my smr address
> 
> 
> 
> wallet
> 
> 

Can you copy and past actual address so I don't have to retype it? Thanks

**Comment by Aryan9592** [comment]
Sure!! Here it is -> smr1qrzxsjqaw04xxwrf3cqlfpja9t4jtw3g4zz0a5yz0z6fetu3exdgky53ul7

Btw, QR Scan feature doesn't work?

**Comment by adamunchained** [comment]
Sent, thank you!

**Pull request merged**
