### PR TITLE
feat: enable bloom iota link

### PR DESCRIPTION
**Pull request by Tuditi**
Adds support for IOTA deep links in Bloom.

### CODE REVIEW

**Review by adamunchained — CHANGES_REQUESTED** [review]
so just to confirm, it's same deeplink and you just decide on the network based on the address?

**Comment by Tuditi** [comment]
Yes, that's correct. I couldn't test end-to-end locally, because I couldn't sign it with Metamask. I tested the deeplink by replacing the addresses on soonaverse.com and testing it out within the browser.

**Comment by Tuditi** [comment]
Hey @adamunchained , is there anything from our end that we need to do to merge this in?

**Comment by adamunchained** [comment]
> Hey @adamunchained , is there anything from our end that we need to do to merge this in?

I've now merged this into develop. There is on going feature development into "bulk purchasing" once that's completed there will be a release and it'll be pushed into prod.

**Pull request merged**
